// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiksvxvcprdprpnhlhqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtpa3N2eHZjcHJkcHJwbmhsaHFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODU2MjQsImV4cCI6MjA1OTI2MTYyNH0.AjcornIO7C8zeKK4i9Polq0hOSP0HITBuQjo2kwMjZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);